[sbert]
sbert = [
    "hkunlp/instructor-large"
]


[cross-encoder]
cross-encoder = [
    "cross-encoder/ms-marco-TinyBERT-L-2"
]

[other]
other = [
    "sentence-transformers/sentence-t5-xxl",
    "sentence-transformers/gtr-t5-xxl",
    "neuralmagic/bge-large-en-v1.5-quant",
    "hkunlp/instructor-large",
    "hkunlp/instructor-xl"

    ]